// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjbqldzafvklllawtecn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqYnFsZHphZnZrbGxsYXd0ZWNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNzQ4MTgsImV4cCI6MjA2NDc1MDgxOH0.SjCHXBQi1dtM_F7GbvIV0XOV9YT5ezYPt-S52DXReto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);